# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SparkXAdDemo_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!
pod 'SparkXAdSDK',:path => '../../SparkXAdSDK'
  # Pods for SparkXAdDemo-Swift

  target 'SparkXAdDemo_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SparkXAdDemo_SwiftUITests' do
    # Pods for testing
  end

end
