# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '9.0'

target 'SparkXAdDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SparkXAdSDK'
  target 'SparkXAdDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SparkXAdDemoUITests' do
    # Pods for testing
  end

end
